removeAnvilXPLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = true
removeAnvilLevelLimit = true
fairLevelCost = true
removeRepairCostIncrease = true
newAnvilLevelLimit = 2555
